runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /images
    static_dir: images
  - url: /assets
    static_dir: assets
  - url: /home-assets
    static_dir: home-assets
  - url: /resume-assets
    static_dir: resume-assets
  - url: /.*
    script: main.app

libraries:
  - name: jinja2
    version: latest
