runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /images
    static_dir: images
  - url: /assets
    static_dir: assets
  - url: /assets/home
    static_dir: assets/home
  - url: /assets/resume
    static_dir: assets/resume
  - url: /files
    static_dir: files/
  - url: /.*
    script: main.app

libraries:
  - name: jinja2
    version: latest
